DROP DATABASE IF EXISTS books_db;
CREATE DATABASE books_db;
USE books_db;

CREATE TABLE books(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  authorId INTEGER(11),
  title VARCHAR(100)
);

CREATE TABLE authors(
  id INTEGER(11) AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(30),
  lastName VARCHAR(30)
);
