DROP DATABASE IF EXISTS ice_creamDB;
CREATE DATABASE ice_creamDB;
USE ice_creamDB;

DROP TABLE IF EXISTS products;

CREATE TABLE products(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  flavor VARCHAR(45) NULL,
  price DECIMAL(10,2) NULL,
  quantity INT NULL
)