DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;

CREATE TABLE books(
  id INTEGER PRIMARY KEY,
  authorId INTEGER UNSIGNED,
  title VARCHAR(100)
);

CREATE TABLE authors(
  id INTEGER PRIMARY KEY,
  firstName VARCHAR(100),
  lastName VARCHAR(100)
);
